### ISSUE TITLE
Errors when Running the EEG file

### ISSUE THREAD

**Issue by hmmcgowan** [mscaudill/Deep_Seize#1]
I was able to clone the files an use them in python.  I have created iter and load. I also created a next. I was not sure if it would be helpful at all. I created it only so that I could tell how the iter was working.

When I run the eeg class, it always gives me an error. Everthing within the class works properly despite the errors. I do not receive any errors when running the view instance file.
I am using Spyeder in anaconda for python. Let my know if you have any suggestions
for how to resolve the errors.

this is the output when I run the eeg file:
    runfile('C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py', wdir='C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize')
Traceback (most recent call last):

  File "<ipython-input-167-c4f828666e16>", line 1, in <module>
    runfile('C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py', wdir='C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize')

  File "C:\Users\Xue_Lab\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\Xue_Lab\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py", line 6, in <module>
    from deep_seize.mixins.view_instance import ViewInstance

ModuleNotFoundError: No module named 'deep_seize'

I can eliminate that error by commenting out line 6. Since I run the view instance file on its own it works without that line.  If I do that this is the output:
    
runfile('C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py', wdir='C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize')
Traceback (most recent call last):

  File "<ipython-input-171-c4f828666e16>", line 1, in <module>
    runfile('C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py', wdir='C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize')

  File "C:\Users\Xue_Lab\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\Xue_Lab\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py", line 177, in <module>
    eeg = EDF('data/sample/sample1.edf', channel=0)

  File "C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py", line 49, in __init__
    self.file_info = self.fetch_file_info()

  File "C:/Users/Xue_Lab/Documents/GitHub/Deep_Seize/eeg.py", line 57, in fetch_file_info
    with pyedflib.EdfReader(self.file_path) as stream:

  File "pyedflib\_extensions\_pyedflib.pyx", line 116, in pyedflib._extensions._pyedflib.CyEdfReader.__init__

  File "pyedflib\_extensions\_pyedflib.pyx", line 155, in pyedflib._extensions._pyedflib.CyEdfReader.open

  File "pyedflib\_extensions\_pyedflib.pyx", line 127, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok

OSError: can not open file, no such file or directory

**Comment by mscaudill** [comment]
Holly,

1. Notice that your __iter__ will return all the samples of the instance no matter whether the instance is sliced or not. This is not incorrect. A client will expect it to return only the samples in the current slice of the instance. e.g.
eeg = EDF(...)
a = eeg[0:10]
for el in a:
     print(el)
this should print out only samples 0 to 10. Your iter version will print all the samples in the file

2. Your load function is also problematic. It reads the entire signal in and then slices the numpy array. It would be better if this method sliced the instance first and then returns only the elements needed.

I'll stop by to chat about the errors your getting
